# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_CLIENT_ID"
name = "xenon-view"
handle = "xenon-view-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "YOUR_STORE_DOMAIN.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
